### ISSUE TITLE
URL with an URL in it

### ISSUE THREAD

**Issue by dkarlovi** [brefphp/symfony-bridge#53]
Let's say I deploy a Symfony6+Bref powered Lambda and access it via URL like this:
https://my-lambda.aws.amazon.com/proxy/https://example.com

Dumping the request URL like this:

```php
// vendor/bref/symfony-bridge/src/Http/KernelAdapter.php:38
error_log(__METHOD__ .': '. $request->getUri());
```

gives me

```
Bref\SymfonyBridge\Http\KernelAdapter::handle: /proxy/https:/example.com
```

meaning, **one of the slashes gets eaten** by something. It doesn't matter if the URL param is URL-encoded or not, if I pass `//` or `////`, it always ends up as just one slash.

Config looks like this:

```yaml
service: symfony

provider:
    lambdaHashingVersion: 20201221
    name: aws
    region: eu-west-1
    stage: dev
    runtime: provided.al2
    environment:
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    web:
        handler: App\Infrastructure\Symfony\Kernel
        timeout: 1
        layers:
            - ${bref:layer.php-81}
        environment:
            BREF_LOOP_MAX: 100
        events:
            - httpApi: '*'
```

Example of the app used: https://github.com/sigwinhq/pipes
